### ISSUE TITLE
Error: C stack usage  7969424 is too close to the limit

### ISSUE THREAD

**Issue by mdancho84** [lindeloev/job#17]
Hey, awesome package. I had the add-in working, but for some reason I'm now getting C stack usage errors. Any idea why this could be?

![image](https://user-images.githubusercontent.com/13734662/116465237-f52f0100-a83a-11eb-9785-15980ce39a1b.png)

**Comment by lindeloev** [comment]
Thanks for reporting!

Some approaches to narrow this down:

 * try launching the job using code: `job::job({<your code here>})`. If this works, the error is addin specific. If not, continue...
 * try launching the job using code, importing only the necessary stuff: `job::job({<your code here>}`, import = c(only, necessary, vars))`. If this works, you have large "irrelevant" objects in your environment that exceeded your memory limit when copied. If not, continue...
 * You running `object.size(x) / 10^6` on the stuff you import. Are any of them very large? If so, try and `saveRDS()` them, `rm()` them, then add `readRDS()` in your code chunk. This way, they're only ever held in memory once.

Let me know what you learn. We'd better fix this if it's a preventable bug.

**Comment by lindeloev** [comment]
BTW, if you can post a reproducible example, there's a greater chance we can identify this.

**Comment by mdancho84** [comment]
Now that I think about it, I'm betting that the stock data I was using was very large, so this could be why. I'll do some testing and report back with a reproducible issue or if the issue goes away once I don't have such a large dataset in memory.

**Comment by benjamin-elusers** [comment]
Hi Jonas, 

When I saw your package the other day I was very eager to try it.
I have just installed the package on my old macbook pro.
Unfortunately it gave me the same error message when I ran the example code below:
```
job::job({
  foo = 10
  bar = rnorm(5)
})
```
**Error: C stack usage  7969424 is too close to the limit**

Then I updated all packages just to see if there would be any improvement.
And it seemed to work after. Perhaps one dependency should be from a relatively recent version.

```
> R.version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes          

RStudio.Version()
$mode
[1] "desktop"

$version
[1] ‘1.3.1093’

$release_name
[1] "Apricot Nasturtium"

```

**Comment by lindeloev** [comment]
Thanks, @benjamin-elusers, that's certainly a lead but hard to pinpoint. Do you know if your environments were identical before and after upgrading? Particularly, if you had big objects in the environment while doing the pre-upgrade run? By default `job::job()` imports everything so a big environment in the first run could result in that error.

BTW, I'm currently re-writing so that `job::job()` peak memory demand is less. The current GitHub version could peak at 3 x the environment size.

**Comment by benjamin-elusers** [comment]
@lindeloev By default, I never save my environment and nothing should be loaded when I start Rstudio session.
To be honest, I am not entirely sure my environment was completely fresh. But in my case, I doubt that my environment should have been a problem. At most I had 1Gb combining all objects out of 16Gb of RAM. 

I must say that I tried on my linux workstation and it worked immediately with no error.
The R/Rstudio version are from there. 

From this test case, I assumed that the error came from dependencies cause my macbook has rstudio "1.2.5019 - Elderflower" and the packages are updated less frequently (e.g. rstudioapi).
That's why I updated the packages on my macbook, and I reported that it solved the issue for me.

Hope this can help a bit.

**Comment by benjamin-elusers** [comment]
@lindeloev By default, I never save my environment and nothing should be loaded when I start Rstudio session.
To be honest, I am not entirely sure my environment was completely fresh. But in my case, I doubt that my environment should have been a problem. At most I had 1Gb combining all objects out of 16Gb of RAM. 

I must say that I tried on my linux workstation and it worked immediately with no error.
The R/Rstudio version are from there. 

From this test case, I assumed that the error came from dependencies cause my macbook has rstudio "1.2.5019 - Elderflower" and the packages are updated less frequently (e.g. rstudioapi).
That's why I updated the packages on my macbook, and I reported that it solved the issue for me.

Hope this can help a bit.

**Comment by lindeloev** [comment]
`job` depends on the most recent version of `rstudioapi`, so unless that wasn't upgraded on `remotes::git_install()`, that's probably not the issue. Hmm. 

Anyway, I'm closing for now but will keep this in mind. The next version is almost a complete re-write, so fingers crossed that these issues have been fixed in there.
