### ISSUE TITLE
Alternative (streamlined) synthax

### ISSUE THREAD

**Issue by stemangiola** [lindeloev/job#47]
Very cool package.

I was wondering to lower the burden of programming do you think these alternatives could be implemented?

Slight improvement in my opinion

```r
results = job({ brm(model2, data) })
```

This would be game changer. (Would lazy evaluation work here?)
```r
results = data %>% slow_process_1() %>% slow_process_2() %>% job()
```

Or if there is no operator to delay the evaluation something like this would allow to drop the job() line and execute the commands normally

```r
results = 
 {
   data %>% 
   slow_process_1() %>%
   slow_process_2() 
 } %>%
 job()

```

**Comment by lindeloev** [comment]
Those would be really neat! Unfortunately, the `rstudioapi::jobRunScript()` (and related functions) are quite inflexible - they only allow for inserting the job variables into the global workspace upon completion, so you'd need to know the name of the variable assigned-to (`result` in your example). That's why it's "inside" the job() call currently. I'd be thrilled to learn if there's a way to get the name `result` from inside `job()` with the syntax you propose above!

So I think the way to go would be to build a new function (probably a new package) using promises/futures (e.g., the `future` and/or `callr` packages) at the cost of then not being able to track the progress in the RStudio jobs pane.

**Comment by stemangiola** [comment]
Thanks a lot I see, I did not know an API existed. Yes future is great, but I have to say that Rstudio jobs are neat!

Good luck with further development.
