### ISSUE TITLE
Including `devtools::load_all` package is creating an error

### ISSUE THREAD

**Issue by CGMossa** [lindeloev/job#48]
I'm getting this error
```
2021-11-15 19:14:28: Job started. Attaching packages: rscripts, lubridate, patchwork, ggfortify, broom, forcats, dplyr, purrr, readr, tidyr, tibble, ggplot2, tidyverse, stringr, zeallot, searcher, testthat, glue, devtools, usethis, magrittr, fcuk...Error in library(x, ...) : there is no package called 'rscripts'
Calls: sourceWithProgress ... FUN -> suppressMessages -> withCallingHandlers -> library
Execution halted
```
And `rscripts` is the name of the pseudo package I've created to keep track of my functions, etc. in this project that I'm assembling..

So I have a call like this:
```
devtools::load_all()
```

I suspect this is due to `.package()`. So running this I get:
```r
> .packages() %>% print
 [1] "rscripts"  "lubridate" "patchwork" "ggfortify" "broom"     "forcats"   "dplyr"     "purrr"     "readr"    
[10] "tidyr"     "tibble"    "ggplot2"   "tidyverse" "stringr"   "stats"     "graphics"  "grDevices" "utils"    
[19] "datasets"  "zeallot"   "searcher"  "testthat"  "glue"      "devtools"  "usethis"   "magrittr"  "fcuk"     
[28] "methods"   "base"  
```

Alright, so that's where the problem lies..

Is this an issue that can be dealt with in this package? 

I'll make a work-around for my purpose.

**Comment by CGMossa** [comment]
the workaround is 
```r
job::job({}, packages = setdiff(.packages(), setdiff(.packages(), installed.packages()))
```

**Comment by lindeloev** [comment]
Sorry for being *very* late to reply to this!

Yes, each job is a blank session that needs to be set up to replicate the desired parts of your R session. Currently, `job` simply calls `library()` on the packages loaded in the main session and that fails when the package is not installed.

Your solution is good, but not one I would implement automatically because the missing package may cause untransparent errors and for reasons stated [here](https://hohenfeld.is/posts/check-if-a-package-is-installed-in-r/) about `installed.packages()`.

## A manual fix
Here is an even more manual solution. It's easy to understand and loads the pseudopackage within the job.

```r
job::job({
    devtools::load_package()  # Load not-installed package within the job
    print("this is my script")
}, packages = setdiff(.packages(), c("rscripts"))  # Exclude some packages
```

You can load packages outside of your current directory using `devtools::load_all("../my_package/")`.


## To do: a more helpful error
I do not want to add `devtools` or other dependencies so an automation of the "manual fix" is not an option. I also think it's dangerous to simply *not* load a package and would much rather defer it to the user to manually control that via the `options` argument.

However, I think it we can point the user towards a solution with a more helpful error message. Within the job, loop over `success = require(package_name)` and then throw a helpful error if `success == FALSE`, e.g., pointing to this issue.

**Comment by lindeloev** [comment]
The new version released on CRAN contains a partial fix for this. It will now alert the user if packages are loaded that are not in .libPaths() and not try loading them. Hence the job won't error while loading and you can simply do:

```r
job::job({
    devtools::load_package()  # ... or however you load your custom package.
    # your code here
})
```
