### ISSUE TITLE
Kill slow running job?

### ISSUE THREAD

**Issue by bshor** [lindeloev/job#63]
Thanks for creating this great package and publicizing on social media, which is how I found it! :) 

My question: is there a way to kill slow running jobs? I need to launch tasks using the rollama package that typically takes 15s, but if it messes up could take 5 minutes. I'd like to kill a task that runs say longer than 20s. Could jobs do something like this?

**Comment by lindeloev** [comment]
Yes! `job::job()` silently returns the job's id. You can put a timeout-based termination of the job using the {later} package.

```r
# Define somewhere early in your script
cancel_job_if_running = function(job_id) {
  if (rstudioapi::jobList()[[job_id]]$state_description == "running")
    rstudioapi::jobSetState(job_id, "cancelled")
}

# Start a slow job with a timeout
job_id = job::job({Sys.sleep(10)})  # 10-second job
later::later(\() cancel_job_if_running(job_id), 5)  # Cancel it if it's still running after 5 secs
```


Note: This won't work if you immediately make your main session busy since `later::later()` only executes when the session is idling.

Alternatively, there may be solutions where you spawn a new "monitor"-session (from main of from within the job) in parallel that kills the session based on a timeout, but that seems desperate 😅

**Comment by lindeloev** [comment]
Although this is neat, I'd like to see more user requests before adding this feature in `job` itself (like `job::job({code}, timeout = 20)`). Including {later} as an extra dependency is not worth it if this is a rare need.

**Comment by bshor** [comment]
Very cool. I will try this out.
